server:
  port: 9001
logging:
  level:
    com.wei.gulimall: debug
aliyunOss:
  endpoint: oss-cn-guangzhou.aliyuncs.com
  accessKeyId: LTAI5t9UAyAPCBR7de9UeQNA
  accessKeySecret: vIkwNLuYydYAsNNHGUAfGpLBXREHkz
  bucketName: hongwlimei-guall